// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/PostSubtitle.tsx";
import * as $$$$$$1 from "./sections/SliderSection.tsx";
import * as $$$$$$2 from "./sections/SobreMim.tsx";
import * as $$$$$$3 from "./sections/PostHeader.tsx";
import * as $$$$$$4 from "./sections/NewsletterSection.tsx";
import * as $$$$$$5 from "./sections/Footer.tsx";
import * as $$$$$$6 from "./sections/PostVideo.tsx";
import * as $$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$8 from "./sections/AreaDeAtuação.tsx";
import * as $$$$$$9 from "./sections/PessoasDeVerdade.tsx";
import * as $$$$$$10 from "./sections/PostBigTag.tsx";
import * as $$$$$$11 from "./sections/Feedback.tsx";
import * as $$$$$$12 from "./sections/NoticiasSection.tsx";
import * as $$$$$$13 from "./sections/PostImage.tsx";
import * as $$$$$$14 from "./sections/PostText.tsx";
import * as $$$$$$15 from "./sections/WhatsApp.tsx";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/taissanutriws/sections/AreaDeAtuação.tsx": $$$$$$8,
    "deco-sites/taissanutriws/sections/Feedback.tsx": $$$$$$11,
    "deco-sites/taissanutriws/sections/Footer.tsx": $$$$$$5,
    "deco-sites/taissanutriws/sections/Header.tsx": $$$$$$7,
    "deco-sites/taissanutriws/sections/NewsletterSection.tsx": $$$$$$4,
    "deco-sites/taissanutriws/sections/NoticiasSection.tsx": $$$$$$12,
    "deco-sites/taissanutriws/sections/PessoasDeVerdade.tsx": $$$$$$9,
    "deco-sites/taissanutriws/sections/PostBigTag.tsx": $$$$$$10,
    "deco-sites/taissanutriws/sections/PostHeader.tsx": $$$$$$3,
    "deco-sites/taissanutriws/sections/PostImage.tsx": $$$$$$13,
    "deco-sites/taissanutriws/sections/PostSubtitle.tsx": $$$$$$0,
    "deco-sites/taissanutriws/sections/PostText.tsx": $$$$$$14,
    "deco-sites/taissanutriws/sections/PostVideo.tsx": $$$$$$6,
    "deco-sites/taissanutriws/sections/SliderSection.tsx": $$$$$$1,
    "deco-sites/taissanutriws/sections/SobreMim.tsx": $$$$$$2,
    "deco-sites/taissanutriws/sections/WhatsApp.tsx": $$$$$$15,
  },
  "apps": {
    "deco-sites/taissanutriws/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/taissanutriws",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
